Parameters:
    EnvironmentBuild:
        Description: This is used as a tag for this account
        Type: String

    VpcCIDR:
        Description: This is the VPC ip network for the underlining Infrastructure
        Type: String
        Default: 10.0.0.0/16

    PublicSubnet1CIDR:
        Description: This is the public Subnet1 cidr notation
        Type: String
        Default: 10.0.0.0/24

    PublicSubnet2CIDR:
        Description: This is the public Subnet2 cidr notation
        Type: String
        Default: 10.0.1.0/24

    PrivateSubnet1CIDR:
        Description: This is the private Subnet1 cidr notation
        Type: String
        Default: 10.0.2.0/24

    PrivateSubnet2CIDR:
        Description: This is the private Subnet2 cidr notation
        Type: String
        Default: 10.0.3.0/24

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            Tags:
                - Key: name
                  Value: !Ref EnvironmentBuild

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: name
                  Value: !Ref EnvironmentBuild

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC

    PublicSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 0, !GetAZs '' ]
            CidrBlock: !Ref PublicSubnet1CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentBuild} Public Subnet (AZ1)

    PublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            CidrBlock: !Ref PublicSubnet2CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentBuild} Public Subnet (AZ2)

    PrivateSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 0, !GetAZs '' ]
            CidrBlock: !Ref PrivateSubnet1CIDR
            MapPublicIpOnLaunch: false
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentBuild} Private Subnet (AZ1)

    PrivateSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            CidrBlock: !Ref PrivateSubnet2CIDR
            MapPublicIpOnLaunch: false
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentBuild} Private Subnet (AZ2)
