Parameters:

    EnvironmentBuild:
        Description: This is used as a tag for this account
        Type: String

Resources:
    LBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow httpd to our load balancer
            VpcId:
                Fn::ImportValue:
                    !Sub ${EnvironmentBuild}-VPCID
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0

    WebServerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: This allow httpd and ssh
            VpcId:
                Fn::ImportValue:
                    !Sub ${EnvironmentBuild}-VPCID
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: 0.0.0.0/0

    WebAppLaunchConfig:
        Type: AWS::Autoscaling::LaunchConfiguration
        Properties:
            UserData:
              Fn::Base64: !Sub |
                #!/bin/bash
                # Install Docker
                apt-get update
                apt-get install \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg-agent \
                software-properties-common
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) \
                stable"
                apt-get update
                apt-get install -y docker-ce
                usermod -aG docker ubuntu
                docker run -p 8080:8080 tomcat:8.0
            ImageId: ami-005bdb005fb00e791
            KeyName: nasiru
            SecurityGroups:
            - Ref: WebServerSecurityGroup
            InstanceType: t3.medium
            BlockDeviceMappings:
            - DeviceName: "/dev/sdk"
              Ebs:
                volumeSize: '10'

    WebAppGroup:
        Type: AWS::Autoscaling::AutoscalingGroup
        Properties:
            VPCZoneIdentifier:
            - Fn::ImportValue:
                !Sub ${EnvironmentBuild}-Private-Subnets
            LaunchConfigurationName:
              Ref: WebAppLaunchConfig
            MinSize: '3'
            MaxSize: '5'
            
